### ISSUE TITLE
Replace Math.E in interest.js with non-imaginary compounding formula

### ISSUE THREAD

**Issue by cfarm** [CapitalJS/capitaljs#5]
Specify compound rate/number in interest.js.

Compound frequency should be an input instead of using continuous compounding interest with Math.E, for example, 12 compounds per year, one per year, daily, etc.

Example calculator for reference:
http://www.thecalculatorsite.com/articles/finance/compound-interest-formula.php

**Comment by contolini** [comment]
@wpears We're killing _e_ because it turns out no bank in the world compounds interest continuously. We've been mad with <sup>power</sup>.

**Comment by contolini** [comment]
:+1:
